import { atlasAssetPaths, atlasFeatureMedia } from "@/content/space/atlas-assets";
import {
  atlasCollectionSchema,
  type PlanetaryWorld,
  type WorldId,
  type WorldMode,
} from "@/lib/space/atlas-schema";

const sources = {
  sdo: {
    id: "nasa-sdo",
    title: "Solar Dynamics Observatory Data",
    publisher: "NASA/GSFC",
    url: "https://sdo.gsfc.nasa.gov/data/",
  },
  mercury: {
    id: "usgs-mercury",
    title: "MESSENGER Global Products",
    publisher: "USGS Astrogeology",
    url: "https://astrogeology.usgs.gov/search/map/mercury-messenger-global-products",
  },
  venus: {
    id: "usgs-venus",
    title: "Venus Magellan Global Products",
    publisher: "USGS Astrogeology",
    url: "https://astrogeology.usgs.gov/search/map/venus-magellan-global-products",
  },
  earth: {
    id: "nasa-blue-marble",
    title: "Blue Marble: Next Generation",
    publisher: "NASA Visible Earth",
    url: "https://visibleearth.nasa.gov/images/57723/the-blue-marblea?size=all",
  },
  earthNight: {
    id: "nasa-black-marble",
    title: "Earth at Night: Black Marble",
    publisher: "NASA Visible Earth",
    url: "https://visibleearth.nasa.gov/images/144898/earth-at-night-black-marble-2016-color-maps/144957l",
  },
  moon: {
    id: "nasa-moon-kit",
    title: "CGI Moon Kit: LROC Color and LOLA Elevation",
    publisher: "NASA Scientific Visualization Studio",
    url: "https://svs.gsfc.nasa.gov/4720",
  },
  mars: {
    id: "usgs-mars",
    title: "Mars Viking Global Color Mosaic",
    publisher: "USGS Astrogeology",
    url: "https://astrogeology.usgs.gov/search/map/mars_viking_global_color_mosaic_925m",
  },
  marsGlobalMap: {
    id: "usgs-mars-global-map",
    title: "Digital Global Geologic Map of Mars",
    publisher: "USGS Astrogeology Science Center",
    url: "https://www.usgs.gov/publications/digital-global-geologic-map-mars-chronostratigraphic-ages-topographic-and-crater",
  },
  marsMola: {
    id: "nasa-mars-mola",
    title: "Mars Global Surveyor MOLA Topography and Ocean Visualization",
    publisher: "NASA Scientific Visualization Studio",
    url: "https://svs.gsfc.nasa.gov/2291/",
  },
  marsPerseveranceWater: {
    id: "nasa-perseverance-water",
    title: "Perseverance Science Highlights: Jezero Water History",
    publisher: "NASA/JPL-Caltech",
    url: "https://science.nasa.gov/mission/mars-2020-perseverance/science-highlights/",
  },
  marsMaven: {
    id: "nasa-maven",
    title: "MAVEN Observations of Martian Atmospheric Loss",
    publisher: "NASA Goddard / MAVEN",
    url: "https://science.nasa.gov/missions/maven/nasas-maven-makes-first-observation-of-atmospheric-sputtering-at-mars/",
  },
  jupiter: {
    id: "nasa-jupiter",
    title: "Jupiter 3D Model and Mission Resources",
    publisher: "NASA Science",
    url: "https://science.nasa.gov/resource/jupiter-3d-model/",
  },
  saturn: {
    id: "nasa-saturn",
    title: "Saturn 3D Model and Mission Resources",
    publisher: "NASA Science",
    url: "https://science.nasa.gov/resource/saturn-3d-model/",
  },
  iceGiants: {
    id: "nasa-ice-giants",
    title: "Ice Giant Resources and Voyager Imagery",
    publisher: "NASA Science",
    url: "https://science.nasa.gov/solar-system/resources/resource-packages/ice-giant-resources/",
  },
};

const atlasInput = {
  id: "atlas-of-worlds",
  title: "Atlas of Worlds",
  worlds: [
    {
      id: "sun",
      name: "Sun",
      orderLabel: "Central star",
      classification: "G-type main-sequence star",
      accent: "#d77a38",
      shortDescription: "A restless star whose magnetic field shapes every world in this atlas.",
      overview:
        "The Sun contains almost all the mass in the Solar System. Its visible surface is a turbulent plasma, while ultraviolet observatories reveal loops, active regions, and the million-degree corona above it.",
      defaultModeId: "photosphere",
      physical: {
        type: "Star",
        radiusKm: 695700,
        gravity: "274 m/s²",
        dayLength: "25–35 Earth days",
        meanTemperature: "5,500 °C surface",
        distance: "System centre",
      },
      assets: atlasAssetPaths.sun,
      renderer: {
        kind: "sun",
        axialTilt: 7.25,
        rotationSeconds: 150,
        atmosphereColor: "#ff8a36",
        emissiveIntensity: 1.65,
      },
      modes: [
        { id: "photosphere", label: "Photosphere", description: "The visible surface in processed warm light.", visibleChange: "Uses a processed warm-light SDO image with an accelerated motion visualization of fine surface-plasma convection.", evidence: "processed", effect: "surface", lighting: "hidden", motion: "solar" },
        { id: "171", label: "171 Å", description: "Extreme ultraviolet light tracing quiet coronal loops.", visibleChange: "Uses processed SDO 171 Å imagery with a wavelength-specific accelerated motion visualization confined to the observed image surface.", evidence: "processed", effect: "texture", textureKey: "171", lighting: "hidden", motion: "solar", legend: [{ label: "171 Å", detail: "Coronal loops · about 0.6 million K", color: "#d7c96c" }] },
        { id: "193", label: "193 Å", description: "Hot coronal plasma and dark coronal holes.", visibleChange: "Uses processed SDO 193 Å imagery with an accelerated motion visualization of hotter coronal structure within the observed image surface.", evidence: "processed", effect: "texture", textureKey: "193", lighting: "hidden", motion: "solar", legend: [{ label: "193 Å", detail: "Corona · about 1.2 million K", color: "#b8cf75" }] },
        { id: "304", label: "304 Å", description: "Chromosphere and transition-region plasma.", visibleChange: "Uses processed SDO 304 Å imagery with an accelerated motion visualization confined to chromospheric structure in the observed image.", evidence: "processed", effect: "texture", textureKey: "304", lighting: "hidden", motion: "solar", legend: [{ label: "304 Å", detail: "Chromosphere · about 50,000 K", color: "#e67e45" }] },
        { id: "magnetic", label: "Magnetic activity", description: "Representative active regions and solar-cycle evidence.", visibleChange: "Adds a restrained magnetic-field visualization around observed active-region locations.", evidence: "inferred", effect: "magnetic", lighting: "hidden", motion: "none" },
        { id: "interior", label: "Interior", description: "A helioseismology-informed model of the solar interior.", visibleChange: "Replaces the photosphere with a clipped model of the core, radiative zone, and convection zone.", evidence: "inferred", effect: "interior", lighting: "hidden", motion: "none" },
      ],
      hotspots: [
        {
          id: "sunspot-region",
          label: "Active region",
          category: "Magnetism",
          lat: 16,
          lon: -24,
          summary: "Dark sunspots mark where concentrated magnetic fields suppress convection.",
          detail: "Sunspots are cooler than the surrounding photosphere but still intensely hot. Their twisted magnetic fields can store energy later released in flares and coronal mass ejections.",
          evidence: "observed",
          coordinateConfidence: "representative",
          sourceIds: ["nasa-sdo"],
          modeIds: ["photosphere", "magnetic"],
          measurements: [{ label: "Typical lifetime", value: "Days to months" }, { label: "Field strength", value: "Up to ~0.4 T" }],
          media: atlasFeatureMedia["sun-active-region"],
        },
        {
          id: "coronal-loop",
          label: "Coronal loop",
          category: "Corona",
          lat: -22,
          lon: 38,
          summary: "Arcs of plasma trace magnetic field lines high above the visible surface.",
          detail: "Extreme-ultraviolet wavelengths isolate plasma at different temperatures, revealing bright material constrained by magnetic fields rather than a solid atmospheric structure.",
          evidence: "processed",
          coordinateConfidence: "representative",
          sourceIds: ["nasa-sdo"],
          modeIds: ["171", "193", "304"],
          measurements: [{ label: "Temperature", value: "~1 million K" }, { label: "Span", value: "Tens of thousands km" }],
        },
        {
          id: "convection-zone",
          label: "Convection zone",
          category: "Interior",
          lat: 0,
          lon: 0,
          summary: "The outer interior transports energy through rolling columns of plasma.",
          detail: "Helioseismology uses oscillations at the visible surface to infer motions and boundaries inside the Sun. The convection zone occupies roughly the outer thirty percent by radius.",
          evidence: "inferred",
          coordinateConfidence: "representative",
          sourceIds: ["nasa-sdo"],
          modeIds: ["interior"],
          measurements: [{ label: "Inner boundary", value: "~0.71 solar radius" }, { label: "Evidence", value: "Helioseismology" }],
        },
      ],
      sources: [sources.sdo],
      interiorLayers: [
        { label: "Core", radiusRatio: 0.25, color: "#fff3a6", state: "Fusion plasma" },
        { label: "Radiative zone", radiusRatio: 0.7, color: "#f8bd52", state: "Dense plasma" },
        { label: "Convection zone", radiusRatio: 0.96, color: "#e97d38", state: "Convecting plasma" },
        { label: "Photosphere", radiusRatio: 1, color: "#ffd27b", state: "Visible plasma" },
      ],
    },
    {
      id: "mercury",
      name: "Mercury",
      orderLabel: "1st planet",
      classification: "Rocky world",
      accent: "#8c8177",
      shortDescription: "A metal-rich world recording four billion years of bombardment and contraction.",
      overview: "MESSENGER revealed a cratered planet with enormous impact basins, long contractional cliffs, polar ice in permanent shadow, and an iron core unusually large for its size.",
      defaultModeId: "surface",
      physical: { type: "Terrestrial planet", radiusKm: 2439.7, gravity: "3.70 m/s²", dayLength: "58.6 Earth days", meanTemperature: "167 °C", distance: "57.9 million km from Sun" },
      assets: atlasAssetPaths.mercury,
      renderer: { kind: "solid", axialTilt: 0.034, rotationSeconds: 170, bumpScale: 0.035, roughness: 0.92 },
      modes: [
        { id: "surface", label: "Surface", description: "MESSENGER global color and morphology.", visibleChange: "Shows the calibrated MESSENGER surface mosaic with elevation-derived relief.", evidence: "processed", effect: "surface", lighting: "natural-survey", motion: "none" },
        { id: "basins", label: "Basins", description: "Major impact structures and contractional terrain.", visibleChange: "Emphasizes impact relief and brings the Caloris Basin into a readable inspection angle.", evidence: "observed", effect: "hotspots", lighting: "natural-survey", motion: "none" },
        { id: "temperature", label: "Temperature", description: "The extreme day-to-night thermal range.", visibleChange: "Applies a day-to-night thermal color gradient with hot, temperate, and cold legend values.", evidence: "inferred", effect: "temperature", lighting: "hidden", motion: "none", legend: [{ label: "Day", detail: "Up to about 430 °C", color: "#f2b24f" }, { label: "Night", detail: "Down to about −180 °C", color: "#527aa8" }] },
        { id: "missions", label: "Missions", description: "Mariner 10 and MESSENGER observation history.", visibleChange: "Adds a representative MESSENGER orbital path and mission observation marker.", evidence: "observed", effect: "missions", lighting: "natural-survey", motion: "none" },
        { id: "interior", label: "Interior", description: "A gravity-informed model dominated by the core.", visibleChange: "Replaces the surface with a clipped model showing Mercury's unusually large metallic core.", evidence: "inferred", effect: "interior", lighting: "hidden", motion: "none" },
      ],
      hotspots: [
        { id: "caloris", label: "Caloris Basin", category: "Impact basin", lat: 30.5, lon: 162.7, summary: "One of the Solar System's largest impact basins spans about 1,550 km.", detail: "The Caloris impact excavated a vast multi-ring basin. Later volcanic plains flooded parts of the floor, while jumbled terrain formed near the antipode.", evidence: "observed", coordinateConfidence: "sourced", sourceIds: ["usgs-mercury"], modeIds: ["surface", "basins"], measurements: [{ label: "Diameter", value: "~1,550 km" }, { label: "Age", value: "~3.9 billion years" }], media: atlasFeatureMedia["mercury-caloris"] },
        { id: "polar-ice", label: "Polar cold traps", category: "Volatiles", lat: 88.5, lon: 45, summary: "Radar-bright deposits persist inside craters that never receive direct sunlight.", detail: "MESSENGER measurements support water ice and dark organic-rich material in permanently shadowed northern polar craters despite Mercury's proximity to the Sun.", evidence: "inferred", coordinateConfidence: "approximate", sourceIds: ["usgs-mercury"], modeIds: ["surface", "temperature"], measurements: [{ label: "Temperature", value: "Below ~−170 °C" }, { label: "Setting", value: "Permanent shadow" }] },
        { id: "discovery-science", label: "MESSENGER orbit", category: "Mission", lat: 12, lon: -48, summary: "The first spacecraft to orbit Mercury mapped the entire planet from 2011 to 2015.", detail: "MESSENGER measured composition, topography, gravity, magnetic field, and exosphere before ending with a planned surface impact.", evidence: "observed", coordinateConfidence: "representative", sourceIds: ["usgs-mercury"], modeIds: ["missions"], measurements: [{ label: "Orbital mission", value: "2011–2015" }, { label: "Orbits", value: ">4,000" }] },
      ],
      sources: [sources.mercury],
      interiorLayers: [
        { label: "Solid inner core", radiusRatio: 0.42, color: "#f1c27d", state: "Solid metal" },
        { label: "Liquid outer core", radiusRatio: 0.82, color: "#c87945", state: "Liquid metal" },
        { label: "Mantle", radiusRatio: 0.94, color: "#8f5f45", state: "Silicate rock" },
        { label: "Crust", radiusRatio: 1, color: "#8a8179", state: "Solid rock" },
      ],
    },
    {
      id: "venus",
      name: "Venus",
      orderLabel: "2nd planet",
      classification: "Cloud-covered rocky world",
      accent: "#d59b55",
      shortDescription: "An Earth-sized planet transformed by a crushing carbon-dioxide atmosphere.",
      overview: "Venus hides beneath sulfuric-acid clouds. Radar mapping reveals volcanic plains, tessera highlands, and great shield volcanoes beneath an atmosphere hot enough to melt lead at the surface.",
      defaultModeId: "radar",
      physical: { type: "Terrestrial planet", radiusKm: 6051.8, gravity: "8.87 m/s²", dayLength: "243 Earth days", meanTemperature: "464 °C", distance: "108.2 million km from Sun" },
      assets: atlasAssetPaths.venus,
      renderer: { kind: "venus", axialTilt: 177.4, rotationSeconds: 210, atmosphereColor: "#e6b66d", bumpScale: 0.02, cloudOpacity: 0.82 },
      modes: [
        { id: "radar", label: "Radar surface", description: "Magellan radar brightness mapped as a surface reconstruction.", visibleChange: "Removes the visible cloud deck and reveals the Magellan radar surface with processed relief.", evidence: "processed", effect: "texture", textureKey: "radar", lighting: "natural-survey", motion: "none" },
        { id: "atmosphere", label: "Atmosphere", description: "The global sulfuric-acid cloud deck.", visibleChange: "Shows the opaque sulfuric-acid cloud shell with subtle super-rotation motion.", evidence: "observed", effect: "atmosphere", lighting: "natural-survey", motion: "clouds" },
        { id: "volcanoes", label: "Volcanoes", description: "Large volcanic provinces and possible recent activity.", visibleChange: "Keeps the radar surface visible and focuses authored volcanic provinces such as Maat Mons.", evidence: "inferred", effect: "hotspots", lighting: "natural-survey", motion: "none" },
        { id: "missions", label: "Missions", description: "Magellan radar mapping and Venera surface exploration.", visibleChange: "Adds mission observation paths and the Venera 13 surface location to the radar globe.", evidence: "observed", effect: "missions", lighting: "natural-survey", motion: "none" },
        { id: "interior", label: "Interior", description: "An Earth-like internal model with large uncertainties.", visibleChange: "Replaces the clouds with a clipped, explicitly uncertain model of Venus's interior.", evidence: "inferred", effect: "interior", lighting: "hidden", motion: "none" },
      ],
      hotspots: [
        { id: "maat-mons", label: "Maat Mons", category: "Volcano", lat: 0.9, lon: 194.5 - 180, summary: "A giant shield volcano rising roughly eight kilometres above the mean radius.", detail: "Magellan radar images reveal lava flows and a complex summit. Changes between radar observations have been interpreted as possible evidence of recent volcanic activity.", evidence: "inferred", coordinateConfidence: "sourced", sourceIds: ["usgs-venus"], modeIds: ["radar", "volcanoes"], measurements: [{ label: "Relief", value: "~8 km" }, { label: "Evidence", value: "Radar morphology" }], media: atlasFeatureMedia["venus-maat-mons"] },
        { id: "maxwell-montes", label: "Maxwell Montes", category: "Highlands", lat: 65.2, lon: 3.3, summary: "The highest mountain range on Venus rises about eleven kilometres.", detail: "Maxwell Montes stands within Ishtar Terra. Radar-bright high elevations may be coated by minerals stable only in the cooler conditions found at altitude.", evidence: "processed", coordinateConfidence: "sourced", sourceIds: ["usgs-venus"], modeIds: ["radar"], measurements: [{ label: "Maximum height", value: "~11 km" }, { label: "Region", value: "Ishtar Terra" }] },
        { id: "venera-13", label: "Venera 13", category: "Mission", lat: -7.5, lon: 303 - 360, summary: "A Soviet lander returned colour panoramas and surface measurements in 1982.", detail: "Venera 13 survived for 127 minutes under about ninety times Earth's sea-level pressure, analysing basaltic soil and transmitting panoramic images.", evidence: "observed", coordinateConfidence: "approximate", sourceIds: ["usgs-venus"], modeIds: ["missions"], measurements: [{ label: "Surface time", value: "127 minutes" }, { label: "Pressure", value: "~9.2 MPa" }] },
      ],
      sources: [sources.venus],
      interiorLayers: [
        { label: "Core", radiusRatio: 0.5, color: "#d58a47", state: "Likely iron-rich" },
        { label: "Lower mantle", radiusRatio: 0.82, color: "#b96f45", state: "Silicate rock" },
        { label: "Upper mantle", radiusRatio: 0.97, color: "#8f563c", state: "Silicate rock" },
        { label: "Crust", radiusRatio: 1, color: "#c59a6a", state: "Basaltic rock" },
      ],
    },
    {
      id: "earth",
      name: "Earth",
      orderLabel: "3rd planet",
      classification: "Ocean world",
      accent: "#4e8fae",
      shortDescription: "A tectonically active ocean planet wrapped in a thin, living atmosphere.",
      overview: "Earth's visible surface is a changing combination of rock, water, ice, clouds, and life. Satellite composites make global patterns legible while night imagery reveals the uneven geography of human settlement.",
      defaultModeId: "surface",
      physical: { type: "Terrestrial planet", radiusKm: 6371, gravity: "9.81 m/s²", dayLength: "23 h 56 min", meanTemperature: "15 °C", distance: "149.6 million km from Sun" },
      assets: atlasAssetPaths.earth,
      renderer: { kind: "earth", axialTilt: 23.44, rotationSeconds: 180, atmosphereColor: "#7bc7ff", bumpScale: 0.018, cloudOpacity: 0.62 },
      modes: [
        { id: "surface", label: "Surface", description: "NASA Blue Marble land, ocean, and ice.", visibleChange: "Shows the Blue Marble surface in legible Survey light by default, with Natural sunlight available.", evidence: "processed", effect: "surface", lighting: "natural-survey", motion: "none" },
        { id: "clouds", label: "Clouds", description: "A separate moving global cloud layer.", visibleChange: "Adds an independently moving observed cloud shell above the Survey-lit surface.", evidence: "processed", effect: "clouds", textureKey: "clouds", lighting: "natural-survey", motion: "clouds" },
        { id: "night-lights", label: "Night lights", description: "Black Marble observations of artificial light after dark.", visibleChange: "Switches to an emissive Black Marble night-light composite without external lighting controls.", evidence: "processed", effect: "night", textureKey: "night", lighting: "hidden", motion: "none" },
        { id: "tectonics", label: "Tectonics", description: "Plate boundaries expressed through representative sites.", visibleChange: "Adds a restrained plate-boundary overlay and focuses representative collision and subduction sites.", evidence: "inferred", effect: "hotspots", lighting: "natural-survey", motion: "none" },
        { id: "atmosphere", label: "Atmosphere", description: "The thin scattering shell that makes a blue limb.", visibleChange: "Strengthens the thin blue atmospheric limb while preserving the visible surface beneath it.", evidence: "inferred", effect: "atmosphere", lighting: "natural-survey", motion: "none" },
        { id: "interior", label: "Interior", description: "A seismic model of crust, mantle, and core.", visibleChange: "Replaces the surface with a clipped seismic model of crust, mantle, and core.", evidence: "inferred", effect: "interior", lighting: "hidden", motion: "none" },
      ],
      hotspots: [
        { id: "himalaya", label: "Himalaya", category: "Tectonics", lat: 27.988, lon: 86.925, summary: "Continental collision raised Earth's highest mountain range.", detail: "The Indian plate continues to converge with Eurasia, thickening the crust and raising the Himalaya. Mount Everest reaches 8,849 metres above sea level.", evidence: "observed", coordinateConfidence: "sourced", sourceIds: ["nasa-blue-marble"], modeIds: ["surface", "tectonics"], measurements: [{ label: "Everest elevation", value: "8,849 m" }, { label: "Setting", value: "Continental collision" }], media: atlasFeatureMedia["earth-himalaya"] },
        { id: "mariana", label: "Mariana Trench", category: "Ocean", lat: 11.35, lon: 142.2, summary: "The deepest known ocean point lies almost eleven kilometres below sea level.", detail: "At Challenger Deep, the Pacific plate bends and descends beneath the Mariana plate. Pressure exceeds one thousand times that at sea level.", evidence: "observed", coordinateConfidence: "sourced", sourceIds: ["nasa-blue-marble"], modeIds: ["surface", "tectonics"], measurements: [{ label: "Depth", value: "~10,935 m" }, { label: "Pressure", value: ">100 MPa" }] },
        { id: "nile-night", label: "Nile at night", category: "Human geography", lat: 27, lon: 31, summary: "A luminous river corridor crosses an otherwise dark desert.", detail: "Black Marble composites show settlement concentrated along the Nile and its delta, making water and population geography visible from orbit.", evidence: "processed", coordinateConfidence: "approximate", sourceIds: ["nasa-black-marble"], modeIds: ["night-lights"], measurements: [{ label: "Composite", value: "2016 annual" }, { label: "Signal", value: "Artificial night light" }] },
      ],
      sources: [sources.earth, sources.earthNight],
      interiorLayers: [
        { label: "Inner core", radiusRatio: 0.19, color: "#f4cf75", state: "Solid iron alloy" },
        { label: "Outer core", radiusRatio: 0.55, color: "#d98543", state: "Liquid iron alloy" },
        { label: "Mantle", radiusRatio: 0.99, color: "#9f5b3f", state: "Solid, slowly convecting rock" },
        { label: "Crust", radiusRatio: 1, color: "#8b9275", state: "Solid rock" },
      ],
    },
    {
      id: "moon",
      name: "Moon",
      orderLabel: "Earth's satellite",
      classification: "Airless rocky world",
      accent: "#9b8d7f",
      shortDescription: "An ancient impact archive whose poles preserve water ice in permanent shadow.",
      overview: "The Moon's craters, dark basaltic maria, bright highlands, and enormous far-side basin record the early Solar System. LRO imagery and laser altimetry turn that record into a measurable globe.",
      defaultModeId: "surface",
      physical: { type: "Natural satellite", radiusKm: 1737.4, gravity: "1.62 m/s²", dayLength: "27.3 Earth days", meanTemperature: "−20 °C", distance: "384,400 km from Earth" },
      assets: atlasAssetPaths.moon,
      renderer: { kind: "solid", axialTilt: 6.68, rotationSeconds: 195, bumpScale: 0.055, roughness: 0.98 },
      modes: [
        { id: "surface", label: "Surface", description: "LROC colour mosaic with restrained relief.", visibleChange: "Shows the LROC global mosaic with restrained LOLA-derived relief and selectable landmarks.", evidence: "processed", effect: "surface", lighting: "natural-survey", motion: "none" },
        { id: "missions", label: "Missions", description: "Crewed and robotic landing sites at sourced coordinates.", visibleChange: "Adds landing-site markers and a mission trail for Apollo 11 and Chandrayaan-3.", evidence: "observed", effect: "missions", lighting: "natural-survey", motion: "none" },
        { id: "water-ice", label: "Water & ice", description: "Permanently shadowed polar cold traps.", visibleChange: "Focuses the south polar region and overlays the permanently shadowed cold-trap zone.", evidence: "inferred", effect: "hotspots", lighting: "natural-survey", motion: "none" },
        { id: "topography", label: "Topography", description: "LOLA elevation drives deliberately exaggerated relief.", visibleChange: "Increases the labelled LOLA relief scale and adds a low-to-high elevation legend.", evidence: "processed", effect: "surface", reliefScale: 0.11, lighting: "natural-survey", motion: "none", legend: [{ label: "Low", detail: "Lower relative elevation", color: "#596b86" }, { label: "High", detail: "Higher relative elevation", color: "#d8c69f" }] },
        { id: "interior", label: "Interior", description: "A seismic and gravity-informed internal model.", visibleChange: "Replaces the surface with a clipped model of the lunar crust, mantle, and small core.", evidence: "inferred", effect: "interior", lighting: "hidden", motion: "none" },
        { id: "lighting", label: "Lighting", description: "Move the Sun to read crater relief and the terminator.", visibleChange: "Enables direct azimuth and elevation control so crater relief and the terminator can be studied.", evidence: "illustrative", effect: "lighting", lighting: "angle", motion: "none" },
      ],
      hotspots: [
        { id: "apollo-11", label: "Apollo 11", category: "Mission", lat: 0.674, lon: 23.473, summary: "Humanity's first crewed lunar landing reached Mare Tranquillitatis in 1969.", detail: "Neil Armstrong and Buzz Aldrin landed Eagle after taking partial manual control beyond a boulder field. Their surface stay returned samples and direct observations from a basaltic plain.", evidence: "observed", coordinateConfidence: "sourced", sourceIds: ["nasa-moon-kit"], modeIds: ["surface", "missions"], measurements: [{ label: "Landing", value: "20 July 1969" }, { label: "Coordinates", value: "0.674°N, 23.473°E" }], media: atlasFeatureMedia["moon-apollo-11"] },
        { id: "chandrayaan-3", label: "Chandrayaan-3", category: "Mission", lat: -69.373, lon: 32.32, summary: "Vikram made the first soft landing in the lunar south-polar region in 2023.", detail: "The lander and Pragyan rover measured the local plasma and thermal environment and confirmed several elements in the regolith at high southern latitude.", evidence: "observed", coordinateConfidence: "sourced", sourceIds: ["nasa-moon-kit"], modeIds: ["missions"], measurements: [{ label: "Landing", value: "23 August 2023" }, { label: "Latitude", value: "69.373°S" }] },
        { id: "south-pole-ice", label: "South Pole ice", category: "Volatiles", lat: -89.5, lon: 0, summary: "Some permanently shadowed crater floors preserve detected water ice.", detail: "With almost no direct sunlight, polar cold traps remain cold enough to retain volatile material. Spectral, radar, neutron, and impact observations provide complementary evidence.", evidence: "inferred", coordinateConfidence: "approximate", sourceIds: ["nasa-moon-kit"], modeIds: ["water-ice", "lighting"], measurements: [{ label: "Cold-trap temperature", value: "Below −150 °C" }, { label: "Illumination", value: "Permanent shadow" }] },
        { id: "tycho", label: "Tycho crater", category: "Impact", lat: -43.3, lon: -11.4, summary: "A young 85-kilometre crater broadcasts bright ejecta rays across the near side.", detail: "Tycho's sharp rim, central peak, terraced walls, and long ray system make it an unusually legible complex impact crater on the lunar surface.", evidence: "observed", coordinateConfidence: "sourced", sourceIds: ["nasa-moon-kit"], modeIds: ["surface", "topography", "lighting"], measurements: [{ label: "Diameter", value: "~85 km" }, { label: "Depth", value: "~4.8 km" }] },
      ],
      sources: [sources.moon],
      interiorLayers: [
        { label: "Inner core", radiusRatio: 0.14, color: "#e6bd77", state: "Solid metal" },
        { label: "Outer core", radiusRatio: 0.2, color: "#bd744e", state: "Partly liquid metal" },
        { label: "Mantle", radiusRatio: 0.97, color: "#82614f", state: "Silicate rock" },
        { label: "Crust", radiusRatio: 1, color: "#a49a8e", state: "Anorthositic and basaltic rock" },
      ],
    },
    {
      id: "mars",
      name: "Mars",
      orderLabel: "4th planet",
      classification: "Cold desert world",
      accent: "#b35e3c",
      shortDescription: "A rusted world of giant volcanoes, buried ice, and landscapes carved by ancient water.",
      overview: "Mars preserves channels, deltas, sedimentary rocks, glaciers, lava plains, and the largest volcano in the Solar System. Orbiters and rovers read this archive at scales from global topography to mineral grains.",
      defaultModeId: "surface",
      physical: { type: "Terrestrial planet", radiusKm: 3389.5, gravity: "3.71 m/s²", dayLength: "24 h 37 min", meanTemperature: "−63 °C", distance: "227.9 million km from Sun" },
      assets: atlasAssetPaths.mars,
      renderer: { kind: "solid", axialTilt: 25.19, rotationSeconds: 188, atmosphereColor: "#d99872", bumpScale: 0.045, roughness: 0.94 },
      modes: [
        { id: "surface", label: "Surface", description: "Viking global colour mosaic of the Martian surface.", visibleChange: "Shows the Viking global colour mosaic with restrained surface relief.", evidence: "processed", effect: "surface", lighting: "natural-survey", motion: "none" },
        { id: "terrain", label: "Terrain", description: "Relief emphasised from global elevation data.", visibleChange: "Strengthens MOLA-derived relief and adds a low-to-high terrain legend.", evidence: "processed", effect: "surface", reliefScale: 0.09, lighting: "natural-survey", motion: "none", legend: [{ label: "Low", detail: "Basins and northern plains", color: "#4d6f84" }, { label: "High", detail: "Volcanic highlands", color: "#c48255" }] },
        { id: "deep-time", label: "Deep time", description: "Drag through 4.1 billion years of Martian environmental change.", visibleChange: "Keeps the observed terrain from Viking and MOLA fixed while water, ice, haze, and atmosphere transform as explicitly qualified reconstructions.", evidence: "inferred", effect: "deep-time", lighting: "natural-survey", motion: "none" },
        { id: "missions", label: "Missions", description: "Representative lander and rover exploration sites.", visibleChange: "Adds mission-site markers and representative rover traverse paths.", evidence: "observed", effect: "missions", lighting: "natural-survey", motion: "none" },
        { id: "atmosphere", label: "Atmosphere", description: "A thin carbon-dioxide scattering shell.", visibleChange: "Strengthens the thin carbon-dioxide atmospheric limb above the surface.", evidence: "inferred", effect: "atmosphere", lighting: "natural-survey", motion: "none" },
        { id: "interior", label: "Interior", description: "An InSight-informed internal model.", visibleChange: "Replaces the surface with a clipped InSight-informed model of crust, mantle, and core.", evidence: "inferred", effect: "interior", lighting: "hidden", motion: "none" },
      ],
      hotspots: [
        { id: "olympus-mons", label: "Olympus Mons", category: "Volcano", lat: 18.65, lon: -133.8, summary: "The Solar System's largest known volcano rises over twenty kilometres.", detail: "Olympus Mons is a broad shield volcano built by repeated low-viscosity lava flows. Its gentle flanks end in a high basal escarpment.", evidence: "observed", coordinateConfidence: "sourced", sourceIds: ["usgs-mars"], modeIds: ["surface", "terrain"], measurements: [{ label: "Relief", value: "~22 km" }, { label: "Width", value: "~600 km" }], media: atlasFeatureMedia["mars-olympus-mons"] },
        { id: "jezero", label: "Jezero crater delta", category: "Ancient water", lat: 18.38, lon: 77.58, summary: "A preserved river delta records a lake that existed billions of years ago.", detail: "Perseverance landed in Jezero to investigate layered sedimentary rocks, collect samples, and test whether its ancient environments could have preserved signs of microbial life.", evidence: "observed", coordinateConfidence: "sourced", sourceIds: ["nasa-perseverance-water"], modeIds: ["deep-time", "missions"], measurements: [{ label: "Crater diameter", value: "~45 km" }, { label: "Rover arrival", value: "2021" }] },
        { id: "valles-marineris", label: "Valles Marineris", category: "Canyon system", lat: -14, lon: -60, summary: "A canyon system stretches roughly a quarter of the way around Mars.", detail: "Tectonic extension opened deep troughs later modified by landslides, erosion, and possible water-related processes. The system dwarfs Earth's Grand Canyon.", evidence: "observed", coordinateConfidence: "approximate", sourceIds: ["usgs-mars-global-map"], modeIds: ["surface", "terrain", "deep-time"], measurements: [{ label: "Length", value: "~4,000 km" }, { label: "Depth", value: "Up to ~7 km" }] },
      ],
      sources: [
        sources.mars,
        sources.marsGlobalMap,
        sources.marsMola,
        sources.marsPerseveranceWater,
        sources.marsMaven,
      ],
      interiorLayers: [
        { label: "Core", radiusRatio: 0.52, color: "#d47a48", state: "Liquid iron alloy" },
        { label: "Lower mantle", radiusRatio: 0.82, color: "#a75f45", state: "Silicate rock" },
        { label: "Upper mantle", radiusRatio: 0.98, color: "#81503e", state: "Silicate rock" },
        { label: "Crust", radiusRatio: 1, color: "#a95f45", state: "Basaltic rock" },
      ],
    },
    {
      id: "jupiter",
      name: "Jupiter",
      orderLabel: "5th planet",
      classification: "Gas giant",
      accent: "#b98262",
      shortDescription: "A rapidly rotating hydrogen world organised by bands, storms, and a vast magnetic field.",
      overview: "Jupiter has no solid surface to stand on. Its visible belts and zones are cloud tops shaped by fast rotation, deep atmospheric circulation, chemistry, and storms that can outlive generations of observers.",
      defaultModeId: "clouds",
      physical: { type: "Gas giant", radiusKm: 69911, gravity: "24.79 m/s²", dayLength: "9 h 56 min", meanTemperature: "−110 °C cloud tops", distance: "778.5 million km from Sun" },
      assets: atlasAssetPaths.jupiter,
      renderer: { kind: "gas", axialTilt: 3.13, rotationSeconds: 95, atmosphereColor: "#d7b18b", flattening: 0.0649 },
      modes: [
        { id: "clouds", label: "Clouds", description: "Belts, zones, and ammonia cloud structure.", visibleChange: "Uses the processed Cassini cloud map with an accelerated motion visualization of differential zonal jets.", evidence: "processed", effect: "surface", lighting: "natural-survey", motion: "atmosphere" },
        { id: "storms", label: "Storms", description: "Long-lived vortices and turbulent wake systems.", visibleChange: "Focuses the observed Great Red Spot while an accelerated motion visualization circulates its clouds counter-clockwise and deforms the local wake.", evidence: "observed", effect: "hotspots", focusHotspotId: "great-red-spot", lighting: "natural-survey", motion: "atmosphere" },
        { id: "auroras", label: "Auroras", description: "Persistent polar emissions in ultraviolet light.", visibleChange: "Adds an evidence-informed accelerated motion visualization of ultraviolet polar curtains over the processed Cassini cloud map.", evidence: "processed", effect: "atmosphere", lighting: "natural-survey", motion: "atmosphere" },
        { id: "magnetosphere", label: "Magnetosphere", description: "A compressed representation of Jupiter's magnetic domain.", visibleChange: "Replaces geographic callouts with a clearly labelled illustrative magnetic-field model.", evidence: "inferred", effect: "magnetic", lighting: "natural-survey", motion: "none" },
        { id: "interior", label: "Interior", description: "A pressure-informed model with a dilute heavy-element core.", visibleChange: "Replaces the clouds with a clipped model of molecular and metallic hydrogen around a dilute core.", evidence: "inferred", effect: "interior", lighting: "hidden", motion: "none" },
        { id: "moons", label: "Moons", description: "The Galilean satellites as a comparative system.", visibleChange: "Adds a comparative Galilean-moon orbit system rather than reusing storm markers.", evidence: "observed", effect: "missions", lighting: "natural-survey", motion: "none" },
      ],
      hotspots: [
        { id: "great-red-spot", label: "Great Red Spot", category: "Storm", lat: -22.2, lon: -41, renderLat: -18, renderLon: 39, summary: "A vast anticyclonic storm has been observed for at least centuries.", detail: "The Great Red Spot rotates counter-clockwise in Jupiter's southern hemisphere. It is shrinking over long timescales but remains wider than Earth.", evidence: "observed", coordinateConfidence: "representative", sourceIds: ["nasa-jupiter"], modeIds: ["clouds", "storms"], measurements: [{ label: "Width", value: "~14,000 km" }, { label: "Rotation", value: "~4 days" }], media: atlasFeatureMedia["jupiter-great-red-spot"] },
        { id: "north-pole-aurora", label: "North polar aurora", category: "Magnetism", lat: 78, lon: 20, summary: "Powerful auroral ovals remain active around Jupiter's magnetic poles.", detail: "Particles accelerated through Jupiter's magnetosphere collide with the upper atmosphere. Volcanic material from Io helps feed the system.", evidence: "processed", coordinateConfidence: "representative", sourceIds: ["nasa-jupiter"], modeIds: ["auroras", "magnetosphere"], measurements: [{ label: "Observation", value: "Ultraviolet / infrared" }, { label: "Driver", value: "Magnetic currents" }] },
        { id: "io-system", label: "Io flux tube", category: "Moon system", lat: 5, lon: 110, summary: "Jupiter and volcanic Io exchange electrical currents and plasma.", detail: "Io's volcanoes supply sulfur and oxygen ions to a plasma torus. Its motion through Jupiter's field creates a current system with auroral footprints.", evidence: "inferred", coordinateConfidence: "representative", sourceIds: ["nasa-jupiter"], modeIds: ["magnetosphere", "moons"], measurements: [{ label: "Io orbital distance", value: "421,700 km" }, { label: "Interaction", value: "Electromagnetic" }] },
      ],
      sources: [sources.jupiter],
      interiorLayers: [
        { label: "Dilute core", radiusRatio: 0.3, color: "#d7a26d", state: "Heavy elements + metallic hydrogen" },
        { label: "Metallic hydrogen", radiusRatio: 0.78, color: "#b96e6b", state: "Conductive fluid" },
        { label: "Molecular hydrogen", radiusRatio: 0.96, color: "#a98782", state: "Compressed fluid" },
        { label: "Cloud deck", radiusRatio: 1, color: "#d9b899", state: "Ammonia-rich clouds" },
      ],
    },
    {
      id: "saturn",
      name: "Saturn",
      orderLabel: "6th planet",
      classification: "Ringed gas giant",
      accent: "#c5a36d",
      shortDescription: "A low-density gas giant encircled by a dynamically changing disk of ice and rock.",
      overview: "Saturn's muted atmosphere conceals fierce winds and a polar hexagon. Its rings are thin, structured, and temporary on geological timescales, sculpted by resonances and small moons.",
      defaultModeId: "atmosphere",
      physical: { type: "Gas giant", radiusKm: 58232, gravity: "10.44 m/s²", dayLength: "10 h 42 min", meanTemperature: "−140 °C cloud tops", distance: "1.43 billion km from Sun" },
      assets: atlasAssetPaths.saturn,
      renderer: { kind: "rings", axialTilt: 26.73, rotationSeconds: 105, atmosphereColor: "#e3c88b", flattening: 0.09796, ringInner: 1.2, ringOuter: 2.25 },
      modes: [
        { id: "atmosphere", label: "Atmosphere", description: "Subtle belts beneath a high-altitude haze.", visibleChange: "Shows Saturn's calibrated atmosphere with its true oblateness and soft band contrast.", evidence: "processed", effect: "surface", lighting: "natural-survey", motion: "atmosphere" },
        { id: "rings", label: "Rings", description: "Main ring system with real planar geometry.", visibleChange: "Emphasizes the corrected concentric ring geometry, Cassini Division, and ring-plane shadow.", evidence: "processed", effect: "rings", textureKey: "rings", lighting: "natural-survey", motion: "none" },
        { id: "hexagon", label: "Hexagon", description: "The persistent six-sided jet at the north pole.", visibleChange: "Moves the camera to Saturn's north pole and identifies the persistent hexagonal jet.", evidence: "observed", effect: "hotspots", lighting: "natural-survey", motion: "atmosphere" },
        { id: "magnetosphere", label: "Magnetosphere", description: "A compressed representation of Saturn's magnetic domain.", visibleChange: "Shows a restrained, clearly labelled field model without obscuring the planet or breaking the rings.", evidence: "inferred", effect: "magnetic", lighting: "natural-survey", motion: "none" },
        { id: "interior", label: "Interior", description: "A gravity-informed model with helium rain.", visibleChange: "Replaces the atmosphere with a clipped model that identifies Saturn's helium-rain region.", evidence: "inferred", effect: "interior", lighting: "hidden", motion: "none" },
        { id: "moons", label: "Moons", description: "Titan, Enceladus, and ring-moon interactions.", visibleChange: "Adds representative Titan and Enceladus orbits beside the corrected ring system.", evidence: "observed", effect: "missions", lighting: "natural-survey", motion: "none" },
      ],
      hotspots: [
        { id: "north-hexagon", label: "North polar hexagon", category: "Atmosphere", lat: 78, lon: 0, summary: "A six-sided jet stream encircles Saturn's north pole.", detail: "The hexagon is a persistent atmospheric wave embedded in an eastward jet. Cassini observed changes in its colour and surrounding haze with Saturn's seasons.", evidence: "observed", coordinateConfidence: "representative", sourceIds: ["nasa-saturn"], modeIds: ["atmosphere", "hexagon"], measurements: [{ label: "Width", value: "~29,000 km" }, { label: "Wind", value: "~320 km/h" }], media: atlasFeatureMedia["saturn-hexagon"] },
        { id: "cassini-division", label: "Cassini Division", category: "Rings", lat: 0, lon: 38, renderRadius: 1.02, summary: "A dark ring gap is maintained largely by resonance with the moon Mimas.", detail: "The division is not empty; it contains sparse ring material. Orbital resonances remove particles from some paths and concentrate complex wave patterns elsewhere.", evidence: "observed", coordinateConfidence: "representative", sourceIds: ["nasa-saturn"], modeIds: ["rings", "moons"], measurements: [{ label: "Width", value: "~4,800 km" }, { label: "Primary resonance", value: "Mimas 2:1" }] },
        { id: "enceladus-plume", label: "Enceladus plume source", category: "Moon system", lat: -82, lon: 120, renderRadius: 1.34, summary: "Jets from Enceladus feed Saturn's diffuse E ring with water-rich particles.", detail: "Cassini flew through plumes venting from fractures near Enceladus's south pole, sampling salts, organics, silica, and water sourced from a subsurface ocean.", evidence: "observed", coordinateConfidence: "representative", sourceIds: ["nasa-saturn"], modeIds: ["rings", "moons"], measurements: [{ label: "Moon radius", value: "252 km" }, { label: "Material", value: "Water-rich plume" }] },
      ],
      sources: [sources.saturn],
      interiorLayers: [
        { label: "Diffuse core", radiusRatio: 0.36, color: "#cf9b65", state: "Rock, ice, metallic hydrogen" },
        { label: "Metallic hydrogen", radiusRatio: 0.66, color: "#9f6b72", state: "Conductive fluid" },
        { label: "Helium-rain region", radiusRatio: 0.82, color: "#ba8b82", state: "Hydrogen + helium" },
        { label: "Molecular atmosphere", radiusRatio: 1, color: "#d8c08f", state: "Hydrogen-rich fluid" },
      ],
    },
    {
      id: "uranus",
      name: "Uranus",
      orderLabel: "7th planet",
      classification: "Ice giant",
      accent: "#77aeb4",
      shortDescription: "An ice giant rotating almost on its side inside a narrow ring and moon system.",
      overview: "Uranus's blue-green methane haze hides a dynamic atmosphere. Its extreme axial tilt creates decades-long seasons, while its magnetic field is strongly tilted and offset from the planet's centre.",
      defaultModeId: "atmosphere",
      physical: { type: "Ice giant", radiusKm: 25362, gravity: "8.69 m/s²", dayLength: "17 h 14 min", meanTemperature: "−195 °C", distance: "2.87 billion km from Sun" },
      assets: atlasAssetPaths.uranus,
      renderer: { kind: "rings", axialTilt: 97.77, rotationSeconds: 125, atmosphereColor: "#8ad5d2", flattening: 0.0229, ringInner: 1.55, ringOuter: 2.0 },
      modes: [
        { id: "atmosphere", label: "Atmosphere", description: "Methane-rich haze and subtle band structure.", visibleChange: "Shows the methane-rich atmosphere with calibrated haze and subtle cloud-band contrast.", evidence: "processed", effect: "surface", lighting: "natural-survey", motion: "atmosphere" },
        { id: "rings", label: "Rings", description: "Narrow dark rings discovered from stellar occultations.", visibleChange: "Reveals Uranus's narrow, dark concentric rings in the planet's steeply tilted equatorial plane.", evidence: "observed", effect: "rings", textureKey: "rings", lighting: "natural-survey", motion: "none" },
        { id: "axial-tilt", label: "Axial tilt", description: "Rotate to reveal the planet's sideways seasons.", visibleChange: "Adds a calibrated rotation-axis guide that makes Uranus's 97.77-degree tilt immediately legible.", evidence: "observed", effect: "tilt", lighting: "natural-survey", motion: "none" },
        { id: "magnetosphere", label: "Magnetosphere", description: "A tilted, offset magnetic-field model.", visibleChange: "Adds a labelled illustrative magnetic axis visibly offset from the rotation axis.", evidence: "inferred", effect: "magnetic", lighting: "natural-survey", motion: "none" },
        { id: "interior", label: "Interior", description: "A composition model for an ice giant.", visibleChange: "Replaces the haze with a clipped composition model of atmosphere, ionic ocean, and core.", evidence: "inferred", effect: "interior", lighting: "hidden", motion: "none" },
        { id: "moons", label: "Moons", description: "Ariel, Umbriel, Titania, Oberon, and Miranda.", visibleChange: "Adds a representative major-moon orbit system around the sideways planet.", evidence: "observed", effect: "missions", lighting: "natural-survey", motion: "none" },
      ],
      hotspots: [
        { id: "south-season", label: "Extreme seasons", category: "Axial tilt", lat: -72, lon: 0, summary: "Each pole can face decades of continuous sunlight followed by darkness.", detail: "Uranus's rotation axis lies close to its orbital plane. Near solstice, one hemisphere points toward the Sun while the other experiences a long polar night.", evidence: "observed", coordinateConfidence: "representative", sourceIds: ["nasa-ice-giants"], modeIds: ["atmosphere", "axial-tilt"], measurements: [{ label: "Axial tilt", value: "97.77°" }, { label: "Orbital period", value: "84 Earth years" }] },
        { id: "epsilon-ring", label: "Epsilon ring", category: "Rings", lat: 0, lon: 52, summary: "The brightest main ring is narrow, dark, and shepherded by small moons.", detail: "Uranus's rings contain larger, darker particles than Saturn's bright ice-rich rings. The epsilon ring varies in width and is constrained by Cordelia and Ophelia.", evidence: "observed", coordinateConfidence: "representative", sourceIds: ["nasa-ice-giants"], modeIds: ["rings", "moons"], measurements: [{ label: "Discovery", value: "1977" }, { label: "Character", value: "Narrow and dark" }], media: atlasFeatureMedia["uranus-rings"] },
        { id: "magnetic-axis", label: "Offset magnetic axis", category: "Magnetism", lat: 59, lon: -30, summary: "Uranus's magnetic axis is steeply tilted and displaced from its centre.", detail: "Voyager 2 measurements revealed a highly asymmetric magnetosphere. Rotation causes the magnetic tail to twist into a corkscrew-like configuration.", evidence: "inferred", coordinateConfidence: "representative", sourceIds: ["nasa-ice-giants"], modeIds: ["magnetosphere"], measurements: [{ label: "Magnetic tilt", value: "~59°" }, { label: "Source", value: "Voyager 2" }] },
      ],
      sources: [sources.iceGiants],
      interiorLayers: [
        { label: "Rocky core", radiusRatio: 0.22, color: "#a87566", state: "Rock and metal" },
        { label: "Ionic ocean", radiusRatio: 0.72, color: "#5f91a3", state: "Water-ammonia-methane fluid" },
        { label: "Molecular envelope", radiusRatio: 0.93, color: "#6ca6aa", state: "Hydrogen, helium, methane" },
        { label: "Atmosphere", radiusRatio: 1, color: "#9bd2ce", state: "Methane-rich gas" },
      ],
    },
    {
      id: "neptune",
      name: "Neptune",
      orderLabel: "8th planet",
      classification: "Ice giant",
      accent: "#426ea8",
      shortDescription: "A distant blue world with supersonic winds and rapidly evolving dark storms.",
      overview: "Neptune radiates more energy than it receives from the Sun. That internal heat helps drive bright methane-ice clouds, dark vortices, and the fastest measured winds on any planet.",
      defaultModeId: "atmosphere",
      physical: { type: "Ice giant", radiusKm: 24622, gravity: "11.15 m/s²", dayLength: "16 h 6 min", meanTemperature: "−200 °C", distance: "4.50 billion km from Sun" },
      assets: atlasAssetPaths.neptune,
      renderer: { kind: "gas", axialTilt: 28.32, rotationSeconds: 118, atmosphereColor: "#3f78d0", flattening: 0.0171 },
      modes: [
        { id: "atmosphere", label: "Atmosphere", description: "Blue methane haze and bright high clouds.", visibleChange: "Shows Neptune's calibrated methane haze with bright high clouds and subtle atmospheric flow.", evidence: "processed", effect: "surface", lighting: "natural-survey", motion: "atmosphere" },
        { id: "storms", label: "Storms", description: "Transient dark vortices observed by spacecraft and telescopes.", visibleChange: "Focuses the Great Dark Spot and adds subtle animated flow around the transient vortex.", evidence: "observed", effect: "hotspots", focusHotspotId: "great-dark-spot", lighting: "natural-survey", motion: "atmosphere" },
        { id: "winds", label: "Winds", description: "Representative latitude bands for extreme atmospheric flow.", visibleChange: "Overlays restrained directional wind bands with a legend for inferred flow direction.", evidence: "inferred", effect: "hotspots", lighting: "natural-survey", motion: "atmosphere", legend: [{ label: "Zonal flow", detail: "Direction inferred from cloud tracking", color: "#c8e4ff" }] },
        { id: "magnetosphere", label: "Magnetosphere", description: "A tilted, offset magnetic-field model.", visibleChange: "Adds a clearly labelled illustrative magnetic axis tilted and offset from the planet's centre.", evidence: "inferred", effect: "magnetic", lighting: "natural-survey", motion: "none" },
        { id: "interior", label: "Interior", description: "A composition model for a warm ice-giant interior.", visibleChange: "Replaces the atmosphere with a clipped model of Neptune's warm ionic ocean and rocky core.", evidence: "inferred", effect: "interior", lighting: "hidden", motion: "none" },
        { id: "moons", label: "Moons", description: "Triton and Neptune's compact inner moon system.", visibleChange: "Adds Triton's retrograde orbit and representative paths for Neptune's inner moons.", evidence: "observed", effect: "missions", lighting: "natural-survey", motion: "none" },
      ],
      hotspots: [
        { id: "great-dark-spot", label: "Great Dark Spot", category: "Storm", lat: -22, lon: 32, summary: "Voyager 2 observed a large dark vortex that later disappeared.", detail: "Unlike Jupiter's long-lived Great Red Spot, Neptune's dark vortices can emerge and dissipate over years. Bright companion clouds form as air rises and condenses methane ice.", evidence: "observed", coordinateConfidence: "representative", sourceIds: ["nasa-ice-giants"], modeIds: ["atmosphere", "storms"], measurements: [{ label: "Observed", value: "Voyager 2, 1989" }, { label: "Persistence", value: "Transient" }], media: atlasFeatureMedia["neptune-great-dark-spot"] },
        { id: "supersonic-winds", label: "Supersonic winds", category: "Atmosphere", lat: -45, lon: -65, summary: "Neptune's fastest winds approach two thousand kilometres per hour.", detail: "Cloud tracking reveals strong east-west jets. The energy source and momentum transport remain active research questions so far from weak sunlight.", evidence: "inferred", coordinateConfidence: "representative", sourceIds: ["nasa-ice-giants"], modeIds: ["winds"], measurements: [{ label: "Peak speed", value: "~2,100 km/h" }, { label: "Method", value: "Cloud tracking" }] },
        { id: "triton-orbit", label: "Triton's retrograde orbit", category: "Moon system", lat: 15, lon: 140, summary: "Neptune's largest moon orbits backward and is probably a captured world.", detail: "Triton's retrograde, inclined orbit indicates capture from the outer Solar System. Voyager 2 observed young terrain and nitrogen geyser-like plumes.", evidence: "inferred", coordinateConfidence: "representative", sourceIds: ["nasa-ice-giants"], modeIds: ["moons"], measurements: [{ label: "Orbit", value: "Retrograde" }, { label: "Surface", value: "Nitrogen-rich ice" }] },
      ],
      sources: [sources.iceGiants],
      interiorLayers: [
        { label: "Rocky core", radiusRatio: 0.24, color: "#9e7166", state: "Rock and metal" },
        { label: "Ionic ocean", radiusRatio: 0.73, color: "#3e6e9d", state: "Water-ammonia-methane fluid" },
        { label: "Molecular envelope", radiusRatio: 0.94, color: "#385f98", state: "Hydrogen, helium, methane" },
        { label: "Atmosphere", radiusRatio: 1, color: "#4b78bf", state: "Methane-rich gas" },
      ],
    },
  ],
};

export const atlas = atlasCollectionSchema.parse(atlasInput);

export function getWorld(id: WorldId): PlanetaryWorld {
  const world = atlas.worlds.find((item) => item.id === id);
  if (!world) throw new Error(`Unknown Atlas world: ${id}`);
  return world;
}

export function getMode(world: PlanetaryWorld, modeId: string): WorldMode {
  return (
    world.modes.find((mode) => mode.id === modeId) ??
    world.modes.find((mode) => mode.id === world.defaultModeId) ??
    world.modes[0]
  );
}

export function getVisibleHotspots(world: PlanetaryWorld, modeId: string) {
  return world.hotspots.filter((hotspot) => hotspot.modeIds.includes(modeId));
}
