import { celestialBodySchema } from "@/lib/space/schema";

export const earth = celestialBodySchema.parse({
  id: "earth",
  name: "Earth",
  exhibitLabel: "Exhibit 006 · Space",
  tagline: "One planet, seen the way satellites see it.",
  promise:
    "NASA's Blue Marble and Black Marble composites, mapped onto a globe you can turn — the same imagery scientists use, not an illustration of it.",
  radius: 1.6,
  colorTexture: "/media/space/earth-day.jpg",
  nightTexture: "/media/space/earth-night.jpg",
  rotationPeriodSec: 220,
  accent: "#6fb8d9",
  categories: [
    { id: "geography", label: "Geography", color: "#d98f4e" },
    { id: "oceans", label: "Oceans & Ice", color: "#6fb8d9" },
    { id: "lights", label: "Night Lights", color: "#e8c766" },
  ],
  modes: [
    { id: "all", label: "All", description: "Every catalogued site.", categories: "all" },
    {
      id: "geography",
      label: "Geography",
      description: "Landmarks that define the planet's surface.",
      categories: ["geography"],
    },
    {
      id: "oceans",
      label: "Oceans & Ice",
      description: "Water in its three states, at planetary scale.",
      categories: ["oceans"],
    },
    {
      id: "lights",
      label: "Night Lights",
      description: "Switches to NASA's Black Marble — city lights as seen from orbit.",
      categories: ["lights"],
    },
  ],
  hotspots: [
    {
      id: "everest",
      label: "Mount Everest",
      category: "geography",
      lat: 27.988,
      lon: 86.925,
      cameraDistance: 2.4,
      summary: "8,849 m — the highest point on Earth's surface.",
      detail:
        "Everest sits on the border of Nepal and Tibet, still rising a few millimeters a year as the Indian and Eurasian tectonic plates continue to collide.",
      accessibleDescription: "A marker in the Himalayas, on the border of Nepal and Tibet.",
      sourceIds: ["nasa-earth-obs"],
      coordinateConfidence: "sourced",
    },
    {
      id: "amazon",
      label: "Amazon Rainforest",
      category: "geography",
      lat: -3.465,
      lon: -62.216,
      cameraDistance: 2.5,
      summary: "The largest rainforest on Earth, spanning nine countries.",
      detail:
        "At around 5.5 million square kilometers, the Amazon basin holds roughly ten percent of the species scientists have documented on Earth, and its river carries more water than the next seven largest rivers combined.",
      accessibleDescription: "A marker over the Amazon basin in northern South America.",
      sourceIds: ["nasa-earth-obs"],
      coordinateConfidence: "sourced",
    },
    {
      id: "sahara",
      label: "Sahara Desert",
      category: "geography",
      lat: 23.4,
      lon: 8,
      cameraDistance: 2.6,
      summary: "The largest hot desert on Earth — roughly the size of the United States.",
      detail:
        "The Sahara wasn't always dry: around 6,000 years ago it was a savanna with lakes and grassland. Its dust regularly crosses the Atlantic, fertilizing soil in the Amazon.",
      accessibleDescription: "A marker across a vast desert spanning North Africa.",
      sourceIds: ["nasa-earth-obs"],
      coordinateConfidence: "sourced",
    },
    {
      id: "mariana",
      label: "Mariana Trench",
      category: "oceans",
      lat: 11.35,
      lon: 142.2,
      cameraDistance: 2.4,
      summary: "Challenger Deep — nearly 11 km down, the deepest known point in any ocean.",
      detail:
        "The trench formed where the Pacific plate subducts beneath the smaller Mariana plate. The pressure at its deepest point is over 1,000 times that at sea level.",
      accessibleDescription: "A marker over a deep ocean trench east of the Mariana Islands in the western Pacific.",
      sourceIds: ["nasa-earth-obs"],
      coordinateConfidence: "sourced",
    },
    {
      id: "reef",
      label: "Great Barrier Reef",
      category: "oceans",
      lat: -18.3,
      lon: 147.7,
      cameraDistance: 2.5,
      summary: "The world's largest living structure, visible from space.",
      detail:
        "Built by billions of tiny coral polyps over thousands of years, the reef stretches roughly 2,300 km along Australia's northeast coast and supports thousands of marine species.",
      accessibleDescription: "A marker off the northeast coast of Australia, over a long coral reef system.",
      sourceIds: ["nasa-earth-obs"],
      coordinateConfidence: "sourced",
    },
    {
      id: "antarctica",
      label: "Antarctica",
      category: "oceans",
      lat: -82,
      lon: 0,
      cameraDistance: 2.7,
      summary: "Holds about 60% of the world's fresh water, locked as ice.",
      detail:
        "The Antarctic ice sheet averages over 2 km thick. If it fully melted, global sea level would rise by roughly 58 meters.",
      accessibleDescription: "A marker over the ice sheet covering the South Pole.",
      sourceIds: ["nasa-earth-obs"],
      coordinateConfidence: "approximate",
    },
    {
      id: "ring-of-fire",
      label: "Pacific Ring of Fire",
      category: "geography",
      lat: 35.36,
      lon: 138.73,
      cameraDistance: 2.5,
      summary: "A horseshoe of volcanoes and fault lines circling the Pacific — here at Mount Fuji.",
      detail:
        "About 75% of Earth's active volcanoes and 90% of its earthquakes occur along this roughly 40,000 km arc, where the Pacific plate grinds against its neighbors.",
      accessibleDescription: "A marker at Mount Fuji, part of the volcanic arc ringing the Pacific Ocean.",
      sourceIds: ["nasa-earth-obs"],
      coordinateConfidence: "approximate",
    },
    {
      id: "megalopolis",
      label: "Northeast Megalopolis",
      category: "lights",
      lat: 40.5,
      lon: -74.5,
      cameraDistance: 2.3,
      summary: "One continuous glow from Boston to Washington, D.C.",
      detail:
        "This stretch of the US East Coast holds over 50 million people across several metro areas that have grown together into one lit-up corridor, clearly visible in NASA's Black Marble imagery.",
      accessibleDescription: "A marker along the densely lit northeastern coast of the United States.",
      sourceIds: ["nasa-black-marble"],
      coordinateConfidence: "approximate",
    },
    {
      id: "nile",
      label: "The Nile at Night",
      category: "lights",
      lat: 27,
      lon: 31,
      cameraDistance: 2.4,
      summary: "A bright ribbon of light tracing the river through otherwise dark desert.",
      detail:
        "Nearly all of Egypt's population lives within a few kilometers of the Nile. At night the river and its delta appear as one of the most sharply defined bright lines on the entire planet.",
      accessibleDescription: "A marker along the Nile River and its delta in Egypt, bright against the surrounding desert.",
      sourceIds: ["nasa-black-marble"],
      coordinateConfidence: "approximate",
    },
  ],
  sources: [
    {
      id: "nasa-earth-obs",
      title: "Blue Marble: Next Generation",
      publisher: "NASA Earth Observatory",
      url: "https://earthobservatory.nasa.gov/features/BlueMarble",
    },
    {
      id: "nasa-black-marble",
      title: "Night Lights / Black Marble",
      publisher: "NASA Earth Observatory",
      url: "https://earthobservatory.nasa.gov/features/NightLights",
    },
  ],
});
