import { celestialBodySchema } from "@/lib/space/schema";

export const moon = celestialBodySchema.parse({
  id: "moon",
  name: "The Moon",
  exhibitLabel: "Exhibit 005 · Space",
  tagline: "Real spacecraft imagery, not a sculpt.",
  promise:
    "This globe is built from actual Lunar Reconnaissance Orbiter photography — the same craters, the same maria, mapped to the same coordinates the missions actually used.",
  radius: 1.6,
  colorTexture: "/media/space/moon-color.jpg",
  rotationPeriodSec: 190,
  accent: "#cfd8e3",
  categories: [
    { id: "mission", label: "Mission Sites", color: "#d98f4e" },
    { id: "geology", label: "Surface & Craters", color: "#a996d1" },
    { id: "water", label: "Water & Ice", color: "#6fb8d9" },
  ],
  modes: [
    { id: "all", label: "All", description: "Every catalogued site.", categories: "all" },
    {
      id: "mission",
      label: "Mission Sites",
      description: "Where humans and robots have actually landed.",
      categories: ["mission"],
    },
    {
      id: "geology",
      label: "Surface & Craters",
      description: "Craters, maria, and the basins that built them.",
      categories: ["geology"],
    },
    {
      id: "water",
      label: "Water & Ice",
      description: "Permanently shadowed polar craters hold detected water ice.",
      categories: ["water"],
    },
  ],
  hotspots: [
    {
      id: "apollo-11",
      label: "Apollo 11",
      category: "mission",
      lat: 0.674,
      lon: 23.473,
      cameraDistance: 2.1,
      summary: "Sea of Tranquility — first crewed lunar landing, July 20, 1969.",
      detail:
        "Neil Armstrong and Buzz Aldrin landed the Eagle here after Armstrong took manual control past a boulder field in the final seconds of descent. They spent about two and a half hours on the surface.",
      accessibleDescription:
        "A marker on the Sea of Tranquility, a dark basaltic plain near the Moon's equator on the near side.",
      sourceIds: ["nasa-apollo11"],
      coordinateConfidence: "sourced",
    },
    {
      id: "apollo-17",
      label: "Apollo 17",
      category: "mission",
      lat: 20.164,
      lon: 30.765,
      cameraDistance: 2.1,
      summary: "Taurus-Littrow — the last Apollo landing, December 1972.",
      detail:
        "Gene Cernan and Harrison Schmitt — the only geologist to walk on the Moon — spent just over three days here, the longest surface stay of the program, and drove the Lunar Roving Vehicle over 35 km.",
      accessibleDescription:
        "A marker in a narrow valley on the edge of the Moon's near-side highlands.",
      sourceIds: ["nasa-apollo17"],
      coordinateConfidence: "sourced",
    },
    {
      id: "chandrayaan-3",
      label: "Chandrayaan-3",
      category: "mission",
      lat: -69.373,
      lon: 32.32,
      cameraDistance: 2.1,
      summary: "Shiv Shakti Point — first landing near the lunar south pole, August 2023.",
      detail:
        "ISRO's Vikram lander touched down in the southern high-latitude highlands, making India the fourth country to land on the Moon and the first to land this close to the south pole.",
      accessibleDescription:
        "A marker in the rugged southern highlands, close to the Moon's south pole.",
      sourceIds: ["isro-chandrayaan3"],
      coordinateConfidence: "sourced",
    },
    {
      id: "tycho",
      label: "Tycho Crater",
      category: "geology",
      lat: -43.3,
      lon: -11.4,
      cameraDistance: 2.6,
      summary: "A young, 108 km crater with a bright ray system that spans the whole disc.",
      detail:
        "Tycho formed about 108 million years ago. Its rays — pulverized material blasted out on impact — are bright enough to be visible without a telescope during a full Moon.",
      accessibleDescription: "A marker on a large, sharply-rimmed crater in the southern highlands.",
      sourceIds: ["usgs-lroc"],
      coordinateConfidence: "approximate",
    },
    {
      id: "copernicus",
      label: "Copernicus Crater",
      category: "geology",
      lat: 9.7,
      lon: -20.1,
      cameraDistance: 2.6,
      summary: "A textbook young impact crater with terraced walls and a central peak.",
      detail:
        "At roughly 93 km across, Copernicus is considered one of the best-preserved examples of a complex lunar crater — its walls slumped into terraces during formation.",
      accessibleDescription: "A marker on a wide, terraced crater in the near side's Oceanus Procellarum region.",
      sourceIds: ["usgs-lroc"],
      coordinateConfidence: "approximate",
    },
    {
      id: "tranquillitatis",
      label: "Mare Tranquillitatis",
      category: "geology",
      lat: 8.5,
      lon: 31,
      cameraDistance: 2.9,
      summary: "A \"sea\" that was never wet — an ancient basaltic lava plain.",
      detail:
        "Early astronomers named the Moon's dark patches maria (\"seas\"), assuming they held water. They're actually flood basalts — lava that filled huge impact basins over three billion years ago and darkened as it cooled.",
      accessibleDescription: "A marker over a large, smooth dark plain on the near side.",
      sourceIds: ["usgs-lroc"],
      coordinateConfidence: "approximate",
    },
    {
      id: "south-pole-aitken",
      label: "South Pole–Aitken Basin",
      category: "geology",
      lat: -53,
      lon: 169,
      cameraDistance: 3.2,
      summary: "One of the largest, oldest confirmed impact basins in the solar system.",
      detail:
        "Roughly 2,500 km across and up to 8 km deep, this far-side basin is old enough that its origin may reveal material from deep in the lunar mantle — a major reason later sample-return missions target this region.",
      accessibleDescription: "A marker spanning a vast, ancient impact basin on the Moon's far side.",
      sourceIds: ["usgs-lroc"],
      coordinateConfidence: "approximate",
    },
    {
      id: "far-side",
      label: "The Far Side",
      category: "geology",
      lat: 2,
      lon: 180,
      cameraDistance: 3.4,
      summary: "Never visible from Earth — first photographed by Luna 3 in 1959.",
      detail:
        "The Moon is tidally locked, so the same hemisphere always faces Earth. The far side is rougher and has far fewer maria than the near side, likely because its crust is thicker.",
      accessibleDescription: "A marker centered on the hemisphere permanently turned away from Earth.",
      sourceIds: ["usgs-lroc"],
      coordinateConfidence: "approximate",
    },
    {
      id: "south-pole-ice",
      label: "South Pole Ice",
      category: "water",
      lat: -89.5,
      lon: 0,
      cameraDistance: 2.3,
      summary: "Permanently shadowed craters here hold detected water ice.",
      detail:
        "Some south polar crater floors never see sunlight and stay below -150°C. India's Chandrayaan-1 carried NASA's Moon Mineralogy Mapper, which found direct spectral evidence of water ice concentrated in these cold traps.",
      accessibleDescription: "A marker at the lunar south pole, where deep crater floors stay in permanent shadow.",
      sourceIds: ["nasa-m3-ice"],
      coordinateConfidence: "approximate",
    },
  ],
  sources: [
    {
      id: "nasa-apollo11",
      title: "Apollo 11 Mission Overview",
      publisher: "NASA",
      url: "https://www.nasa.gov/mission/apollo-11/",
    },
    {
      id: "nasa-apollo17",
      title: "Apollo 17 Mission Overview",
      publisher: "NASA",
      url: "https://www.nasa.gov/mission/apollo-17/",
    },
    {
      id: "isro-chandrayaan3",
      title: "Chandrayaan-3 Mission",
      publisher: "ISRO",
      url: "https://www.isro.gov.in/Chandrayaan3.html",
    },
    {
      id: "usgs-lroc",
      title: "Moon LRO LROC WAC Global Mosaic",
      publisher: "USGS Astrogeology Science Center",
      url: "https://astrogeology.usgs.gov/search/map/moon_lro_lroc_wac_global_morphology_mosaic_100m",
    },
    {
      id: "nasa-m3-ice",
      title: "NASA Radar Finds Ice Deposits at Moon's North Pole / M3 Water Ice Detection",
      publisher: "NASA",
      url: "https://www.nasa.gov/missions/chandrayaan-1/nasa-instrument-finds-direct-evidence-for-water-ice-on-moon/",
    },
  ],
});
